In [3]:
import numpy as np

arr =np.array([1,2,3,4,5,6])

# Represrnt the diamention of the array
print(arr.ndim)
# Size of the array in each diamention
print(arr.shape)
# Total number of element in the array , suppose row = 2 and column =3 then size will be 2*3 = 6
print(arr.size)
#dtype is the element data type inside array
print(arr.dtype)


1
(6,)
6
int32


In [4]:
#reshape will convert the array in new shape with same number of element as the original array

arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
#Create array with zero 

arr_zero = np.zeros(10)

print(arr_zero)

#Create array with zero interger type
arr_zero = np.zeros(10,dtype=np.int64)
print(arr_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]


In [10]:
#Create array with ones
arr_ones = np.ones(10,dtype=np.int64)
print(arr_ones)

[1 1 1 1 1 1 1 1 1 1]


In [11]:
#Create array with arange(start,end,step count)

arr_2 = np.arange(2,10,2)
print(arr_2)

[2 4 6 8]


In [56]:
#Create array with linspace(start,end,number of values in array)
arr_3 = np.linspace(0,10,5)
print(arr_3)

arr_4 = np.linspace(0,20,5)
print(arr_4)

[ 0.   2.5  5.   7.5 10. ]
[ 0.  5. 10. 15. 20.]


In [18]:
#sort element in array
arr_4 = np.array([2,10,1,14,3,15,5])

#sort the array is a copy of array , original array will be remain unchanged
print(np.sort(arr_4))

print(arr_4)

#Add element in an array


[ 1  2  3  5 10 14 15]
[ 2 10  1 14  3 15  5]


In [23]:
#concat 2 array

x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])

np.concatenate((x,y),axis =0) #Axis 0 means join array by row menas increase number of row , number of colun will remain same


array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
# Array arithmetic operation

x = np.array([1,2])
y = np.ones(2,dtype=np.int64)


In [31]:
x + y

array([2, 3], dtype=int64)

In [32]:
x - y

array([0, 1], dtype=int64)

In [33]:
x*y

array([1, 2], dtype=int64)

In [35]:
#Broadcasting --means apply to each elements
array_brod =np.array([2,5,40,7,8,10,22,25])
array_brod*3 # Multiply by 3 with each elements in the array

array([  6,  15, 120,  21,  24,  30,  66,  75])

In [38]:
#Apply filter 
array_brod[array_brod>8]

array([40, 10, 22, 25])

In [43]:
array_brod[(array_brod>8) & (array_brod<20)] # To perform and operation use &

array([10])

In [46]:
array_brod[(array_brod>8) | (array_brod==8)] # To perform or operation use |

array([40,  8, 10, 22, 25])

In [47]:
# Tosave array in file

np.save('array_brod',array_brod)

In [48]:
# To load array from file
new_array = np.load('array_brod.npy')

In [49]:
print(new_array)

[ 2  5 40  7  8 10 22 25]


In [50]:
# Save array in CSV
np.savetxt('array_brod.csv',array_brod)

In [54]:
new_array_csv = np.loadtxt('array_brod.csv')
print(new_array_csv)

[ 2.  5. 40.  7.  8. 10. 22. 25.]
