In [2]:
import numpy as np
import pandas as pd

In [60]:
data={"Name": ["a", "b", "c"],
      "age": [10,20,30]
      }
df = pd.DataFrame(data)

df.sort_index(by='Name')

TypeError: DataFrame.sort_index() got an unexpected keyword argument 'by'

In [62]:
data={"age": [10,20,30,0,5]
      }
df = pd.DataFrame(data)

df['age'].replace(0,df['age'].mean())

0    10
1    20
2    30
3    13
4     5
Name: age, dtype: int64

In [68]:
import pandas as pd

import numpy as np

df = pd.DataFrame(np.random.randn(6, 4), columns=list('ABCD'))
print(df)

df[df.C > 0]


          A         B         C         D
0 -0.095406 -0.514689  0.756544 -1.185581
1 -0.256841  0.970574 -1.399413 -0.106101
2 -0.133211 -1.229158 -0.906562  0.163884
3 -0.235733 -0.820789  0.442299  0.756014
4 -0.196354  0.879314 -0.539076  0.165627
5  0.746547 -0.859247  0.564897 -0.487553


A         B         C         D
0 -0.095406 -0.514689  0.756544 -1.185581
3 -0.235733 -0.820789  0.442299  0.756014
5  0.746547 -0.859247  0.564897 -0.487553

In [81]:
import pandas as pd

data = {

    'Title': ['Inception', 'Dunkirk', 'Interstellar', 'The Prestige', 'Memento'],

    'Director': ['Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan'],

    'Rating': [8.8, 7.9, 8.6, 8.5, 8.4]

}

df = pd.DataFrame(data)
df_f = df[df['Director']=='Christopher Nolan']
df_f['Rating'].mean()


8.440000000000001

In [83]:
import pandas as pd
data = {
    'Product': ['Laptop', 'Desktop', 'Tablet', 'Phone', 'Smartwatch'],
    'Price': [25000, 12000, 8000, 22000, 5000]

}
df = pd.DataFrame(data)
df_f = df[df['Price']>=20000]
print(df_f.sort_values('Price'))

  Product  Price
3   Phone  22000
0  Laptop  25000


In [89]:
import pandas as pd

data = {
    'Store': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Item': ['Apple', 'Banana', 'Orange', 'Grape', 'Apple', 'Banana', 'Orange', 'Grape'],
    'Price': [50, 20, 30, 60, 55, 22, 33, 65],
    'Quantity': [10, 12, 15, 16, 20, 25, 30, 35]
}

df = pd.DataFrame(data)

df['Revenue'] = df['Price'] * df['Quantity']
df_g = df.groupby('Store').agg({'Revenue': 'sum', 'Price': 'mean'}).reset_index()
df_g.rename(columns={'Price': 'Average_Price'}, inplace=True)
df_g


Store  Revenue  Average_Price
0     A     3040          42.00
1     B     4025          41.75

In [92]:
import pandas as pd
data = {
    'Customer': ['Alice', 'Bob', 'Alice', 'Alice', 'Bob', 'Bob', 'Alice', 'Bob'],
    'Item': ['Pen', 'Pencil', 'Notebook', 'Eraser', 'Pen', 'Pencil', 'Notebook', 'Eraser'],
    'Price': [10, 5, 50, 20, 10, 5, 50, 20],
    'Quantity': [3, 4, 2, 5, 10, 6, 1, 2]
}

df = pd.DataFrame(data)
df['Total_Amount_Spent'] = df['Price'] * df['Quantity']
df_g = df.groupby('Customer').agg({'Total_Amount_Spent':sum}).reset_index()
df_g

C:\Users\dutta\AppData\Local\Temp\ipykernel_30956\3588381438.py:11: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df_g = df.groupby('Customer').agg({'Total_Amount_Spent':sum}).reset_index()


Customer  Total_Amount_Spent
0    Alice                 280
1      Bob                 190

In [94]:
import pandas as pd
data = {
    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    'Temperature': [20, 22, 25, 27, 30, 32, 35, 34, 30, 28, 24, 21]
}
df = pd.DataFrame(data)
max_temp = df['Temperature'].max()

df_max = df[df['Temperature']==max_temp]
df_max

Month  Temperature
6   Jul           35

In [95]:
data = {

    'Category': ['Fruit', 'Vegetable', 'Fruit', 'Vegetable', 'Fruit', 'Vegetable'],

    'Name': ['Apple', 'Carrot', 'Banana', 'Potato', 'Grape', 'Onion'],

    'Price': [2, 1, 1.5, 0.5, 3, 1],

    'Quantity': [10, 20, 15, 30, 5, 40]

}



df = pd.DataFrame(data)



fruits = df[df['Category'] == 'Fruit']

total_fruit_value = fruits['Price'].sum() * fruits['Quantity'].sum()

print(total_fruit_value)

195.0


In [96]:
(2+1.5+3) * (10+15+5)

195.0

In [97]:
import pandas as pd



data = {

    'Name': ['Alice', 'Bob', 'Charlie', 'David'],

    'Age': [25, 30, 35, 40],

    'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']

}



df = pd.DataFrame(data)



result = df[df['Age'] >= 30].sort_values(by='Age', ascending=False).iloc[0]['City']

print(result)

Chicago


In [98]:
import pandas as pd



data = {

    'Product': ['A', 'B', 'C', 'A', 'B', 'C'],

    'Price': [100, 200, 300, 150, 250, 350],

    'Quantity': [10, 5, 7, 12, 8, 5]

}



df = pd.DataFrame(data)



total_revenue = (df['Price'] * df['Quantity']).sum()

average_price = df['Price'].mean()

print(total_revenue, average_price)

9650 225.0


In [104]:
import pandas as pd
data = {
    'Customer': ['Alice', 'Bob', 'Alice', 'Alice', 'Bob', 'Bob', 'Alice', 'Bob'],
    'Item': ['Pen', 'Pencil', 'Notebook', 'Eraser', 'Pen', 'Pencil', 'Notebook', 'Eraser'],
    'Price': [10, 5, 50, 20, 10, 5, 50, 20],
    'Quantity': [3, 4, 2, 5, 10, 6, 1, 2]
}

df = pd.DataFrame(data)
df['Total_Amount_Spent'] = df['Price'] * df['Quantity']
df_g = df.groupby(['Item']).agg({'Total_Amount_Spent':sum}).reset_index()

Total_Amount = df_g['Total_Amount_Spent'].sum()

print(df_g)
print(Total_Amount)

       Item  Total_Amount_Spent
0    Eraser                 140
1  Notebook                 150
2       Pen                 130
3    Pencil                  50
470


C:\Users\dutta\AppData\Local\Temp\ipykernel_30956\886106235.py:11: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df_g = df.groupby(['Item']).agg({'Total_Amount_Spent':sum}).reset_index()


In [105]:
import pandas as pd
data = {
    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    'City_A_Temp': [20, 22, 25, 27, 30, 32, 35, 34, 30, 28, 24, 21],
    'City_B_Temp': [10, 12, 15, 17, 20, 22, 25, 24, 20, 18, 14, 11]
}

df = pd.DataFrame(data)
df['Different_Temp'] = df['City_A_Temp'] - df['City_B_Temp']
df

Month  City_A_Temp  City_B_Temp  Different_Temp
0    Jan           20           10              10
1    Feb           22           12              10
2    Mar           25           15              10
3    Apr           27           17              10
4    May           30           20              10
5    Jun           32           22              10
6    Jul           35           25              10
7    Aug           34           24              10
8    Sep           30           20              10
9    Oct           28           18              10
10   Nov           24           14              10
11   Dec           21           11              10

In [8]:
import pandas as pd 
  
data = {"id": [1, 2, 3], 
        "name": ["karthik", "nikhil", "bhagi"]} 
  
df = pd.DataFrame(data) 
print(df)

   id     name
0   1  karthik
1   2   nikhil
2   3    bhagi


In [16]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

result = np.cross(arr1, arr2)

print(result)

[-3  6 -3]


In [23]:
import numpy as np 

arr = np.random.randint(1, 100, size=25).reshape(5,5)

print(np.mean(arr))
print(np.std(arr))

54.36
30.55863871313642


In [28]:
import numpy as np
arr_one = np.identity(5).reshape(5,5)
arr_one= arr_one +5
print(arr_one)
arr_two = np.random.randint(1, 10, size=5).reshape(5,1)
print(arr_two)

arr_mul = np.multiply(arr_one,arr_two)
print(arr_mul)


[[6. 5. 5. 5. 5.]
 [5. 6. 5. 5. 5.]
 [5. 5. 6. 5. 5.]
 [5. 5. 5. 6. 5.]
 [5. 5. 5. 5. 6.]]
[[3]
 [8]
 [2]
 [8]
 [2]]
[[18. 15. 15. 15. 15.]
 [40. 48. 40. 40. 40.]
 [10. 10. 12. 10. 10.]
 [40. 40. 40. 48. 40.]
 [10. 10. 10. 10. 12.]]


In [30]:
import numpy as np
arr_one = np.random.randint(1, 10, size=9).reshape(3,3)
print(arr_one)
arr_two = np.random.randint(1, 10, size=9).reshape(3,3)
print(arr_two)

arr_mul = np.multiply(arr_one,arr_two)
print(arr_mul)

[[7 6 9]
 [2 2 5]
 [8 2 7]]
[[8 5 9]
 [7 2 5]
 [8 7 8]]
[[56 30 81]
 [14  4 25]
 [64 14 56]]


In [32]:
import numpy as np
arr_one = np.random.randint(1, 1001, size=1000)

arr_sum = np.cumsum(arr_one)

print(arr_sum[9])
print(arr_sum[99])
print(arr_sum[499])


5239
50190
252058


In [34]:
import numpy as np
arr_one = np.random.randint(1, 101, size=100).reshape(10,10)

arr_max= np.max(arr_one)
arr_min= np.min(arr_one)

arr_min_index = np.unravel_index(np.argmin(arr_one), arr_one.shape)
arr_max_index = np.unravel_index(np.argmax(arr_one), arr_one.shape)

print(arr_max)
print(arr_min)

print(arr_min_index)
print(arr_max_index)

100
3
(4, 7)
(0, 7)


In [39]:
import numpy as np
arr_one = np.random.rand(5,5)
arr_max= np.max(arr_one)
arr_one[arr_one==arr_max]=0
print(arr_one)


[[0.37213333 0.56216387 0.27841906 0.12717169 0.20387736]
 [0.54902004 0.39289863 0.30561531 0.36918296 0.3979404 ]
 [0.07162005 0.23819216 0.02862499 0.53217685 0.91665793]
 [0.7882424  0.99429151 0.84344224 0.25108496 0.49281276]
 [0.63366795 0.38760816 0.17541255 0.50077628 0.25916103]]
0.9942915083552862
[[0.37213333 0.56216387 0.27841906 0.12717169 0.20387736]
 [0.54902004 0.39289863 0.30561531 0.36918296 0.3979404 ]
 [0.07162005 0.23819216 0.02862499 0.53217685 0.91665793]
 [0.7882424  0.         0.84344224 0.25108496 0.49281276]
 [0.63366795 0.38760816 0.17541255 0.50077628 0.25916103]]


In [41]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B = A[1:3, 0:2]


print(B)
B[0, 0] = 100

print(A)

[[4 5]
 [7 8]]
[[  1   2   3]
 [100   5   6]
 [  7   8   9]]


In [43]:
import numpy as np
arr_one = np.random.randint(1, 101, size=20)

print(arr_one[arr_one%2==0])
print(arr_one[arr_one%2!=0])

[62 22 14 36 76 88 32  2]
[91 45 29 71 79  3 77 61 53  9 99 23]


In [45]:
import numpy as np
A = np.arange(1, 17).reshape(4, 4)
B = A[:, ::-1]
print(B)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [46]:
import numpy as np
arr_one = np.zeros((8, 8))
arr_one[0, :] = 1
arr_one[-1, :] = 1
arr_one[:, 0] = 1
arr_one[:, -1] = 1
print(arr_one)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
